language: go
go:
  - 1.2
  - 1.3
  - tip
branches:
  only:
    - master
install:
  - go get github.com/richardlehane/ac
  - go install github.com/richardlehane/siegfried/pkg/core/bytematcher
  - go install github.com/richardlehane/siegfried/pkg/pronom
  - go install github.com/richardlehane/siegfried/cmd/sieg
script:
  - go test github.com/richardlehane/siegfried/pkg/core/bytematcher
  - go test github.com/richardlehane/siegfried/pkg/pronom
  - go test github.com/richardlehane/siegfried/cmd/sieg